[package]
name = "brood"
version = "0.0.0"
edition = "2021"

[dependencies]
ciborium = "0.2.2"
clap = { version = "4.5.7", features = ["derive", "deprecated"] }
csv = "1.3.0"
rustc-hash = "2.0.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
simd-json = "0.13.10"
