[package]
name = "brood"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.5", features = ["derive"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
