[package]
name = "brood"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive", "deprecated"] }
rustc-hash = "2.0.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
